import React from 'react';
import Landing from './Landing';
import Title from './Title';
import Login from './Login';
import Register from './Register';
import Home from './Home';
import History from './History';
import Dashboard from './Dashboard';
import Result from './Result';
export {Landing, Title, Login, Register, Home, History,Dashboard, Result};
